matplotlib_groupings = {
    "backend layer": ["matplotlib.backend",
                      "matplotlib.blocking",
                      "matplotlib.dviread",
                      "matplotlib.mathtext",
                      "matplotlib.texmanager",
                      "matplotlib.type1font",
                      "matplotlib.widgets"],
    "artist layer": ["matplotlib.afm",
                     "matplotlib.animation",
                     "matplotlib.artist",
                     "matplotlib.ax",
                     "matplotlib.container",
                     "matplotlib.contour",
                     "matplotlib.figure",
                     "matplotlib.gridspec",
                     "matplotlib.hatch",
                     "matplotlib.image",
                     "matplotlib.legend",
                     "matplotlib.lines",
                     "matplotlib.marker",
                     "matplotlib.offset",
                     "matplotlib.patches",
                     "matplotlib.path",
                     "matplotlib.projection",
                     "matplotlib.quiver",
                     "matplotlib.sankey",
                     "matplotlib.scale",
                     "matplotlib.spines",
                     "matplotlib.stackplot",
                     "matplotlib.streamplot",
                     "matplotlib.table",
                     "matplotlib.text",
                     "matplotlib.ticker",
                     "matplotlib.tight",
                     "matplotlib.transforms",
                     "matplotlib.tri.",
                     "matplotlib.units"],
    "scripting layer": ["matplotlib.mlab",
                        "matplotlib.pylab",
                        "matplotlib.pyplot"],
    "configuration": ["matplotlib.rcsetup",
                      "matplotlib.style"],
    "utilities": ["matplotlib.bezier",
                  "matplotlib.cbook",
                  "matplotlib.cm",
                  "matplotlib.collections",
                  "matplotlib.color",
                  "matplotlib.compat",
                  "matplotlib.dates",
                  "matplotlib.delaunay",
                  "matplotlib.docstring",
                  "matplotlib.finance",
                  "matplotlib.font",
                  "matplotlib.sphinxext"]}


module_lookup = dict(list(
    itertools.chain(*[[(x, layer) for x in mod_part]
                      for (layer, mod_part) in matplotlib_groupings.items()])))
